### ISSUE TITLE
5.0.0 release and breaking changes.

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#1571]
This issue is to track the major changes left to be done before we release 5.0.0 and specifically with respect to some proposed breaking changes.

Changes left for 5.0.0:

- [x] #1568 - Ensure we also recycle slave connections with pooling. 
- [x] #1559 - Update XINFO to output a nicer format
- [x] #1168 - Deprecation of various helpers (e.g. `sortAsc`, `sortAlphaAsc`).

Please let us know if removal of the aliased sort methods are going to cause issues for anyone.  I don't even think they're documented so this may be a non issue, but they've been in phpredis for years at this point.

**Comment by yatsukhnenko** [comment]
@michael-grunder all issues are resolved. Is it time to prepare 5.0.0RC1?

**Comment by yatsukhnenko** [comment]
https://pecl.php.net/package/redis/5.0.0RC1
