### ISSUE TITLE
Redis 6.2 support

### ISSUE THREAD

**Issue by remicollet** [phpredis/phpredis#1894]
From [RELEASENOTES](https://github.com/redis/redis/blob/6.2/00-RELEASENOTES)

New commands / args:

- [x]  Add SMISMEMBER command that checks multiple members (#7615)
- [x]  Add ZMSCORE command that returns an array of scores (#7593)
- [x] Add LMOVE and BLMOVE commands that pop and push arbitrarily (#6929)
- [x] Add RESET command that resets client connection state(#7982)
- [x] Add COPY command that copies keys (#7953)
- [x] Add ZDIFF and ZDIFFSTORE commands (#7961)
- [x] Add ZINTER and ZUNION commands (#7794)
- [x] Add GEOSEARCH/GEOSEARCHSTORE commands for bounding box spatial queries (#8094)
- [x] Add GET parameter to SET command, for more powerful GETSET (#7852)
- [x] Add exclusive range query to XPENDING (#8130)
- [x] Add exclusive range query to X[REV]RANGE (#8072)
- [x] Add GT and LT options to ZADD for conditional score updates (#7818)
- [x] Add CLIENT INFO and CLIENT LIST for specific ids (#8113)
- [x] Add IDLE argument to XPENDING command (#7972)
- [x] Add local address to CLIENT LIST, and a CLIENT KILL filter. (#7913)
- [x] Add NOMKSTREAM option to XADD command (#7910)
- [ ] Add command introspection to Sentinel (#7940)
- [x] Add SENTINEL MYID subcommand (#7858)

From **6.2RC2**

- [x] Add the REV, BYLEX and BYSCORE arguments to ZRANGE, and the ZRANGESTORE command (#7844) [#2197]
- [x] Add the XAUTOCLAIM command (#7973)
- [x] Add the MINID trimming strategy and the LIMIT argument to XADD and XTRIM (#8169) [#2172]
- [x] Add the ANY argument to GEOSEARCH and GEORADIUS (#8259)
- [x] Add the CH, NX, XX arguments to GEOADD (#8227)
- [x] Add the COUNT argument to LPOP and RPOP (#8179)
- [x] Add the WRITE argument to CLIENT PAUSE for pausing write commands exclusively (#8170)
- [ ] Change the proto-ver argument of HELLO to optional (#7377)
- [x] Add the CLIENT TRACKINGINFO subcommand (#7309)

From **6.2RC3**

- [x]  Add HRANDFIELD and ZRANDMEMBER commands (#8297)
- [x]  Add FAILOVER command (#8315)
- [x]  Add GETEX, GETDEL commands (#8327)
- [x]  Add PXAT/EXAT arguments to SET command (#8327)
- [x]  Add SYNC arg to FLUSHALL and FLUSHDB, and ASYNC/SYNC arg to SCRIPT FLUSH (#8258)

**Comment by remicollet** [comment]
Notice 5.3.2 test suite passes with redis 6.2RC1 :)

**Comment by yatsukhnenko** [comment]
@michael-grunder @remicollet I think we should create separate PRs for each command and track progress in this issue

**Comment by yatsukhnenko** [comment]
✔️ Add SMISMEMBER command that checks multiple members (#7615)

**Comment by yatsukhnenko** [comment]
exclusive ranges for XPENDING and X[REV]RANGE work without any changes on phpredis side

**Comment by ninthspace** [comment]
Redis 6.2RC2 (12 Jan 2021) has additional commands and changes, which aren't listed above:

* Add the REV, BYLEX and BYSCORE arguments to ZRANGE, and the ZRANGESTORE command (#7844)
* Add the XAUTOCLAIM command (#7973)
* Add the MINID trimming strategy and the LIMIT argument to XADD and XTRIM (#8169)
* Add the ANY argument to GEOSEARCH and GEORADIUS (#8259)
* Add the CH, NX, XX arguments to GEOADD (#8227)
* Add the COUNT argument to LPOP and RPOP (#8179)
* Add the WRITE argument to CLIENT PAUSE for pausing write commands exclusively (#8170)
* Change the proto-ver argument of HELLO to optional (#7377)
* Add the CLIENT TRACKINGINFO subcommand (#7309)

**Comment by yatsukhnenko** [comment]
Thanks @ninthspace

**Comment by crussell52** [comment]
Hi!  Just trying to understand compatibility state.  

I have an existing 6.2 redis server that I would like to attach PHP to.  I don't need to access any of the 6.x Redis features. Is it safe to say that `phpredis` will work as a client so long as I stay within the bounds of the Redis 5 commands?

**Comment by michael-grunder** [comment]
Yes, you should be fine.  AFAIK lots of people are using PhpRedis against Redis 6.0 in production, and I've been using PhpRedis against Redis 6.x pretty much since 6.0 was released.

**Comment by geeksesi** [comment]
hi, i want to use `SMISMEMBER`. 
which version of phpredis should i require in project ?

**Comment by yatsukhnenko** [comment]
@geeksesi try 5.3.5

**Comment by geeksesi** [comment]
@yatsukhnenko 
thank you.
but it's not work.
![image](https://user-images.githubusercontent.com/28778964/147401804-7d43c503-9b64-410f-b24e-a8d2e6d3dc35.png)

![image](https://user-images.githubusercontent.com/28778964/147401810-67eb805b-37ef-4e19-88f1-ca37894399ae.png)

```
        dd(Redis::command('SMISMEMBER', [$this->storedKey, "09245594891"]));
```

- "predis/predis": "dev-main",
- "laravel/framework": "^8.65",
```
php --version
PHP 7.4.27 (cli) (built: Dec 20 2021 21:28:33) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.27, Copyright (c), by Zend Technologies
    with Xdebug v3.1.1, Copyright (c) 2002-2021, by Derick Rethans
```

**Comment by yatsukhnenko** [comment]
@geeksesi it doesn't work because you use Predis 🙃

**Comment by victusfate** [comment]
is geosearch live in release 5.3.7?

**Comment by michael-grunder** [comment]
Closing, as all tasks are done and merged into develop.
