### ISSUE TITLE
Redis 7.0 support

### ISSUE THREAD

**Issue by remicollet** [phpredis/phpredis#2068]
# From [RELEASENOTES](https://github.com/redis/redis/blob/7.0/00-RELEASENOTES)

**New user commands or command arguments**

- [x]  ZMPOP, BZMPOP commands (#9484) [#2165]
- [x]  LMPOP, BLMPOP commands (#9373) [#2165]
- [x]  SINTERCARD, ZINTERCARD commands (#8946, #9425) [#2163]
- [x]  SPUBLISH, SSUBSCRIBE, SUNSUBSCRIBE, PUBSUB SHARDCHANNELS/SHARDNUMSUB (#8621)
- [x]  EXPIRETIME and PEXPIRETIME commands (#8474) [#2166]
- [x]  EXPIRE command group supports NX/XX/GT/LT options (#2795) [#2188]
- [x]  SET command supports combining NX and GET flags (#8906)
- [x]  BITPOS, BITCOUNT accepts BIT index (#9324) [#2185]
- [x]  EVAL_RO, EVALSHA_RO command variants, to run on read-only replicas (#8820) [#2199]
- [x]  SORT_RO command, to run on read-only replicas (#9299) [#2200]
- [ ]  SHUTDOWN arguments: NOW, FORCE, ABORT (#9872)
- [x]  FUNCTION *, FCALL, FCALL_RO - https://redis.io/commands/function-load
- [x]  CONFIG SET/GET can handle multiple configs atomically, in one call (#9748, #9914) [#2192]
- [ ]  QUIT promoted to be a proper command, HOST: and POST demoted (#9798)
- [x]  XADD supports auto sequence number via <ms>-* (#9217)

**New administrative and introspection commands and command arguments**

- [x]  COMMAND DOCS (#9656, #10056, #10104)
- [x]  COMMAND LIST (#9504)
- [x]  COMMAND INFO accepts sub-commands as args, and no args too (#9504, #10056)
- [ ]  LATENCY HISTOGRAM (#9462)
- [ ]  CLUSTER LINKS (#9774)
- [ ]  CLUSTER DELSLOTSRANGE and CLUSTER ADDSLOTSRANGE (#9445)
- [x]  CLIENT NO-EVICT (#8687)
- [x]  ACL DRYRUN (#9974)
- [x]  SLOWLOG GET supports passing in -1 to get all entries (#9018)

**Command replies that have been extended**

- [x]  COMMAND and COMMAND INFO extended with tips, key-specs and sub-commands
- [ ]  see https://redis.io/commands/command
- [x]  ACL CAT, COMMAND LIST list sub-commands (#10127)
- [ ]  MODULE LIST reply includes path and args (#4848)
- [ ]  OBJECT ENCODING returns listpack instead of ziplist (#8887, #9366)
- [ ]  CLUSTER SLOTS hostname support (#9530)
- [x]  COMMAND command: Added the `blocking` and `module` flags (#10104, #9656)

# From 7.0RC2

**New user commands or command arguments**

- [x]   COMMAND GETKEYSANDFLAGS sub-command (#10237)
- [x]   INFO command can take multiple section arguments (#6891) [#2190]
- [x]   XGROUP CREATE and SETID: new ENTRIESREAD optional argument (#9127) [#2196]
- [ ]  XSETID new ENTRIESADDED and MAXDELETEDID optional arguments (#9127)

**Command replies that have been extended**

- [ ]   XINFO reports consumer group lag and a few other fields (#9127)
- [ ]   XAUTOCLAIM returns a new element with a list of deletes IDs (#10227)

**Comment by remicollet** [comment]
Notice: phpredis **5.3.6** test suite passes usig redis **7.0-rc1**

**Comment by yatsukhnenko** [comment]
@michael-grunder are we going to implement other commands from this issue?

**Comment by michael-grunder** [comment]
I'll go through the list today. I think some yes (like the new stream additions) but probably not things like `CLUSTER ADDSLOTS`, etc.

What do you think?

**Comment by yatsukhnenko** [comment]
@michael-grunder XSETID is an internal command, we don't need to implement it.

**Comment by blasto333** [comment]
Will older versions of Phpredis support newer versions of redis if I don’t need the new features of redis

**Comment by michael-grunder** [comment]
Yep, until Redis deprecates `RESP 2` phpredis can talk to the server. I can't imagine that happening any time soon.
